version: '3'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - "./prometheus:/etc/prometheus"

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter

    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

    ports:
      - "9100:9100"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.38.6

    ports:
      - "8080:8080"

    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter

    ports:
      - "9115:9115"

  grafana:
    container_name: grafana
    image: grafana/grafana

    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
      - GF_USERS_ALLOW_SIGN_UP=false

    ports:
      - "3000:3000"

    volumes:
      - "./grafana:/etc/grafana/provisioning"

  alert-manager:
    container_name: alert-manager
    image: prom/alertmanager

    ports:
      - "9093:9093"

  cookery:
    container_name: cookery
    image: quay.io/sirech/cookery2-backend

    ports:
      - "4003:4003"

  echo:
    container_name: echo
    image: quay.io/sirech/echo

    ports:
      - "4000:4000"
