version: '3'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - "./prometheus:/etc/prometheus"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.38.6

    ports:
      - "8080:8080"

    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter

    ports:
      - "9115:9115"

  cookery:
    container_name: cookery
    image: quay.io/sirech/cookery2-backend

    ports:
      - "4003:4003"

  echo:
    container_name: echo
    image: quay.io/sirech/echo

    ports:
      - "4000:4000"
