global:
  scrape_interval: 15s

  external_labels:
    monitor: 'example-prometheus'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s

    static_configs:
      - targets:
          - localhost:9090
          - blackbox-exporter:9115

  - job_name: cadvisor

    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://cookery:4003/rest/recipes
        - http://echo:4000/hello
        - http://echo:4000/fish/zan
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: cookery
    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          - cookery:4003

  - job_name: echo
    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          - echo:4000
